steps:
  # Étape 1 : Construire l'image Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/projet-7-open-scoring/openclassrooms-api:latest', '.']

  # Étape 2 : Pousser l'image sur Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/projet-7-open-scoring/openclassrooms-api:latest']

  # Étape 3 : Déployer sur Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: [
      'run', 'deploy', 'openclassrooms-api',
      '--image', ' gcr.io/projet-7-open-scoring/openclassrooms-api:latest',
      '--platform', 'managed',
      '--region', 'us-central1',
      '--allow-unauthenticated'
    ]


# Les options de configuration (optionnel)
options:
  logging: 'CLOUD_LOGGING_ONLY'
