name: CI/CD Pipeline

on:
  push:
    paths:
      - 'Docker/**'  # Déclencher uniquement pour les changements dans le dossier `docker`

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Checkout du code
      - name: Checkout code
        uses: actions/checkout@v2

      # Étape 2 : Configuration de Google Cloud SDK
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      # Étape 3 : Construire et tester
      - name: Build and Test
        run: |
          docker build -t openclassrooms-api .
          pip install -r requirements.txt
          pytest test/

      # Étape 4 : Pusher l'image Docker et déployer sur Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud builds submit --config cloudbuild.yaml
