name: CI/CD Pipeline

on:
  push:
    branches:
      - Projet-8
    paths:
      - 'Docker/**'  # Déclencher uniquement pour les changements dans le dossier `docker`
      - 'app/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Étape 0 : Extraire le code du dépôt
      - name: Checkout code
        uses: actions/checkout@v3
        
      # Étape 1 : Authentification avec Google Cloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Étape 2A : Configuration de Google Cloud SDK
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      # Étape 2B : Authentification Docker pour GCR
      - name: Authenticate Docker to Google Container Registry
        run: gcloud auth configure-docker
      
      # Étape 2C : Debugging - Lister les fichiers pour vérifier la structure
      - name: List files for debugging
        run: ls -R

      # Étape 2D : Vérifier les permissions du fichier Dockerfile
      - name: Check permissions for Dockerfile
        run: ls -l Docker/Dockerfile

      # Étape 2E : Fix permissions si nécessaire
      - name: Fix permissions for Dockerfile if needed
        run: chmod 644 Docker/Dockerfile

      # Étape 2F : Cacher les dépendances (avec une clé unique pour éviter les problèmes de cache)
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache
          key: ${{ runner.os }}-cache-key-${{ github.run_id }}
          
      # Étape 3 : Construire l'image Docker
      - name: Build Docker image
        run: docker build -f Docker/Dockerfile -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/openclassrooms-api-2:latest .

     # Etape 4 : Tests   
      - name: Run Tests
        run: |
          docker run --rm \
            -e PYTHONPATH=/app \
            -e FLASK_TESTING=true \
            gcr.io/${{ secrets.GCP_PROJECT_ID }}/openclassrooms-api-2:latest \
            python -m pytest tests/ -v
          
      # Étape 5 : Pousser l'image Docker dans Google Container Registry
      - name: Push Docker image to Google Container Registry
        run: docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/openclassrooms-api-2:latest

      # Étape 6 : Déployer sur Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy openclassrooms-api-2 \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/openclassrooms-api-2:latest \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated
