name: CI/CD Pipeline

on:
  push:
    paths:
      - 'Docker/**'  # Déclencher uniquement pour les changements dans le dossier `docker`
      - 'app/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Checkout du code
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2 : Configuration de Google Cloud SDK
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          credentials: ${{ secrets.GCP_SA_KEY }}

      # Étape 3 : Construire l'image Docker
      - name: Build Docker image
        run: docker build -f Docker/Dockerfile -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/openclassrooms-api:latest .
        
      - name: Run Tests
        run: |
          docker run --rm \
            -e PYTHONPATH=/app \
            gcr.io/${{ secrets.GCP_PROJECT_ID }}/openclassrooms-api:latest \
            python -m pytest tests/ -v
          
      # Étape 5 : Pousser l'image Docker dans Google Container Registry
      - name: Push Docker image to Google Container Registry
        run: docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/openclassrooms-api:latest

      # Étape 6 : Déployer sur Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy openclassrooms-api \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/openclassrooms-api:latest \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated
